module.exports.UP = 'UP'
module.exports.DOWN = 'DOWN'
module.exports.IDLE = 'IDLE'

module.exports.ERROR_IMPOSSIBLE_ROUTE = 'ERROR_IMPOSSIBLE_ROUTE'
module.exports.ERROR_ELEVATOR_NOT_REGISTERED = 'ERROR_ELEVATOR_NOT_REGISTERED'
module.exports.ERROR_INVALID_NUMBER_OF_ELEVATORS = 'ERROR_INVALID_NUMBER_OF_ELEVATORS'
